# Common Tables

## Weapons

:::{#weapons-table}
| **Weapon**       | **Cost** | **Type** | **Range** | **Damage**     | **Properties**      |
|------------------|----------|----------|-----------|----------------|---------------------|
| Bastard Sword    | 10 gp    | M        | C         | 1d8 / 1d10     | V, 2 slots          |
| Club             | 5 cp     | M        | C         | 1d4            | —                   |
| Crossbow         | 8 gp     | R        | F         | 1d6            | 2H, L               |
| Dagger           | 1 gp     | M/R      | C/N       | 1d4            | F, Th               |
| Greataxe         | 10 gp    | M        | C         | 1d8 / 1d10     | V, 2 slots          |
| Greatsword       | 12 gp    | M        | C         | 1d12           | 2H, 2 slots         |
| Javelin          | 5 sp     | M/R      | C/F       | 1d4            | Th                  |
| Longbow          | 8 gp     | R        | F         | 1d8            | 2H                  |
| Longsword        | 9 gp     | M        | C         | 1d8            | —                   |
| Mace             | 5 gp     | M        | C         | 1d6            | —                   |
| Shortbow         | 6 gp     | R        | F         | 1d4            | 2H                  |
| Shortsword       | 7 gp     | M        | C         | 1d6            | —                   |
| Spear            | 5 sp     | M/R      | C/N       | 1d6            | Th                  |
| Staff            | 5 sp     | M        | C         | 1d4            | 2H                  |
| Warhammer        | 10 gp    | M        | C         | 1d10           | 2H                  |
:::

:::{.table-caption}
**Table:** Weapons
:::

## Armor

:::{#armor-table}
| **Item**                  | **Cost** | **Slots** | **AC**       | **Properties**             |
|---------------------------|----------|-----------|--------------|----------------------------|
| Leather armor             | 10 gp    | 1         | 11 + DEX mod | —                          |
| Chainmail                 | 60 gp    | 2         | 13 + DEX mod | Disadv on stealth and swim |
| Plate mail                | 130 gp   | 3         | 15           | No swim, disadv on stealth |
| Shield                    | 10 gp    |           | +2           | Occupies one hand          |
| Mithral (metal armor only)| ×4       | -1        | —            | No penalty stealth, swim   |
:::

:::{.table-caption}
**Table:** Armor
:::

:::: {.columns }
::: {.column width="49%" }

### Difficulty Class

- **Easy, DC 9.** Leaping a narrow chasm, sneaking up on an inattentive guard.
- **Normal, DC 12.** Kicking open a stuck door, picking a poor lock.
- **Hard, DC 15.** Swimming against a strong current, giving first aid to stop a character from dying.
- **Extreme, DC 18.** Climbing a slippery cliff one-handed, restraining a frenzied lion

### Morale

Enemies who are reduced to half their number (or half their hit points for a solo enemy) **flee** if they fail a DC 15 Wisdom check.  Large Groups. Make one check using the leader's WIS modifier.

**Large Groups.** Make one check using the leader's WIS modifier.

### Dying

**Death Timer.** 1d4 + CON modifier rounds (min. 1). On turn, roll a d20. 20 = rise with 1 HP.

**Stabilize.** Close range, DC 15 INT check. On success, target stops dying (but is still unconscious)

### Random Encounters

Roll 1d6. 1 = random encounter.

- **Unsafe.** Check every 3 rounds.
- **Risky.** Check every 2 rounds.
- **Deadly.** Check every round

### Distance

| d6  | Starting Distance |
|-----|-------------------|
| 1   | Close             |
| 2-4 | Near              |
| 5-6 | Far               |

### Activity

| 2d6  | Activity            |
|------|---------------------|
| 2-4  | Hunting             |
| 5-6  | Eating              |
| 7-8  | Building/nest       |
| 9-10 | Socializing/playing |
| 11   | Guarding            | 
| 12   | Sleeping            |

### Reaction

| 2d6 + CHA mod | Activity   |
|---------------|------------|
| 0-6           | Hostile    |
| 7-8           | Suspicious |
| 9             | Neutral    |
| 10-11         | Curious    | 
| 12+           | Friendly   |

:::

::: {.column width="2%"}
&nbsp;
:::

::: {.column width="49%"}

### Distance/Movement

- **Close** = 5 feet. **Near** = up to 30 feet. **Far** = within sight.
- **Climbing.** DEX or STR check, half speed. Fall if fail by 5+ points.
- **Falling.** 1d6 damage every 10'.
- **Moving Through.** Move freely through allies. Pass a STR or DEX check to move through enemies.
- **Swimming.** Swim half speed (STR check in rough water). Hold breath for CON mod rounds (min. 1). Then, CON checks or 1d6 damage/rd until exiting hazard.

### Spell Focus

You can't cast other focus spells while focusing. Do a spellcasting check at the start of your turn for the focus spell to maintain it.

- **Success.** The spell stays in effect until the start of your next turn.
- **Failure.** The spell ends. If you were focusing, you do **not** lose the ability to cast that spell.
- **Distraction.** Make a spellcasting check to maintain focus.

### STATS

| **Ability Score** | **Modifier** |
|-------------------|--------------|
| 1–3               | −4           |
| 4–5               | −3           |
| 6–7               | −2           |
| 8–9               | −1           |
| 10–11             | 0            |
| 12–13             | +1           |
| 14–15             | +2           |
| 16–17             | +3           |
| 18+               | +4           |

### Languages

| **Language**    | **Speakers**        |
|-----------------|---------------------|
| Common          | Humanoids           |
| Dwarvish        | Dwarves             |
| Elvish          | Elves               |
| Giant           | Giants              |
| Goblin          | Goblinoids          |
| Merran          | Aquatic folk        |
| Orcish          | Orcs                |
| Reptilian       | Reptile folk        |
| Sylvan          | Fey folk            |
| Thanian         | Beast folk          |
| Celestial (R)   | Angels              |
| Diabolic (R)    | Demons              |
| Draconic (R)    | Dragons             |
| Primordial (R)  | Elder things        |


:::
::::

## XP FOR Treasure Quality

:::{#treasure-quality-xp-table}
| **Quality**   | **XP** | **Examples**                                                |
|---------------|--------|-------------------------------------------------------------|
| Poor          | 0      | Bag of silver, used dagger, knucklebone dice                |
| Normal        | 1      | Bag of gold, gem, fine armor, magic scroll                  |
| Fabulous      | 3      | Magic sword, giant diamond, mithral chainmail               |
| Legendary     | 10     | The Staff of Ord, a djinni’s wish, a dragon hoard           |
:::

:::{.table-caption}
**Table:** Treasure Quality and Experience Awards
:::

## Random Names by Ancestry

:::{#random-names-table}
| **d20** | **Dwarf**  | **Elf**     | **Goblin** | **Halfling** | **Half-Orc** | **Human**  |
|:------:|------------|-------------|------------|--------------|--------------|------------|
| 1  | Hera     | Sarenia   | Kog    | Myrtle   | Troga   | Hesta   |
| 2  | Torin    | Ravos     | Dibbs  | Robby    | Boraal  | Matteo  |
| 3  | Ginny    | Imeria    | Fronk  | Nora     | Urgana  | Rosalin |
| 4  | Gant     | Farond    | Irv    | Percy    | Zoraal  | Endric  |
| 5  | Olga     | Isolden   | Squag  | Daisy    | Scalga  | Kiara   |
| 6  | Dendor   | Kieren    | Mort   | Jolly    | Krell   | Yao     |
| 7  | Ygrid    | Mirenel   | Vig    | Evelyn   | Voraga  | Corina  |
| 8  | Pike     | Riarden   | Sticks | Horace   | Morak   | Rowan   |
| 9  | Sarda    | Allindra  | Gorb   | Willie   | Draga   | Hariko  |
| 10 | Brigg    | Arlomas   | Yogg   | Gertie   | Sorak   | Ikam    |
| 11 | Zorli    | Sylara    | Plok   | Peri     | Varga   | Mariel  |
| 12 | Yorin    | Tyr       | Zrak   | Carlsby  | Ulgar   | Jin     |
| 13 | Jorgena  | Rinariel  | Dent   | Nyx      | Jala    | Hana    |
| 14 | Trogin   | Saramir   | Krik   | Kellan   | Kresh   | Lios    |
| 15 | Riga     | Vedana    | Mizzo  | Fern     | Zana    | Indra   |
| 16 | Barton   | Elindos   | Bort   | Harlow   | Torvash | Remy    |
| 17 | Katrina | Ophelia   | Nabo   | Moira    | Rokara   | Nura    |
| 18 | Egrim    | Cydaros   | Hink   | Sage     | Gartak  | Vakesh  |
| 19 | Elsa     | Tiramel   | Bree   | Reenie   | Iskana  | Una     |
| 20 | Orgo     | Varond    | Kreeb  | Wendry   | Ziraak  | Nabilo  |
:::

:::{.table-caption}
**Table:** Random Names by Ancestry
:::
